config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  devise_for :users
  # devise_for :users, :controllers => {
  #   :registrations => 'devise/registrations'
  # }

  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  # resources :books do
  #   resource :favorites, only: [:create, :destroy]
  # end
  
  # resources :books, except: [:index] do
  #   resource :comments, only: [:create, :destroy]
  # end  
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy  #User.commentsで、ユーザーの所有するコメントを取得できる。
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    flash[:notice] = "Welcome! You have signed up successfully."
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
    flash[:notice] = "Signed in successfully."
  end

  # DELETE /resource/sign_out
  def destroy
    super
    flash[:notice] = "Signed out successfully."
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    end
    def index
        @log_in_user = current_user
        @mybooks = @log_in_user.books
        @users = User.all
        @new_book = Book.new
    end
    
    def show
        @user = User.find(params[:id])
        @new_book = Book.new
        @books = @user.books
        @post_image = @user.profile_image
        
    end
    
    def edit
        @user = User.find(params[:id])
        
        unless current_user.id == @user.id
            redirect_to user_path(current_user.id)
        end
    end
    
    def update
        # @user = ユーザーの取得
        # @user.ユーザーのアップデート
        # redirect_to ユーザーの詳細ページへのパス  
        @user = User.find(params[:id])
        @user.update(user_params)
        
        if @user.update(user_params)
          flash[:notice] = "You have updated user successfully."
          redirect_to user_path(current_user.id)
        else
          render :edit
        end
        
    end
    
    private
    
    def user_params
        params.require(:user).permit(:name, :profile_image, :introduction)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 pt-4 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      
      <% if @user.errors.any? %>
        <div class="errors-box">
          <p><%= @user.errors.count %> errors prohibited this book from being saved:</p>
    
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, id: "inputName", class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="inputImage">Image</label>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*", class: "form-control-file"%>
        </div>
        <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
          <%= f.text_field :introduction, id:"inputIntroduction", class: "form-control" %>
        </div>
        <%= f.submit "Update User" %>
        
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container pt-4 px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
        <%= render partial: 'layouts/side', locals: { user: @log_in_user, new_book: @new_book } %>
    </div>
    
    <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        
        <table class="table mb-5">
            <tbody>
                <tr>
                    <td>Image</td>
                    <td>Name</td>
                    <td></td>
                </tr>
                <% @users.each do |user| %>
                  <tr>
                    <td><%= image_tag user.get_profile_image(80,80) %></td>
                    <td><%= user.name %></td>
                    <td><%= link_to "Show", user_path(user.id) %></td>
                  </tr>
                <% end %>
            </tbody>
        </table>    
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p id = "notice"><%= flash[:notice] %></p>
<% end %>
<div class="container pt-4 px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: 'layouts/side', locals: { user: @user, new_book: @new_book } %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      
      <table class="table mb-5">
          <tbody>
              <tr>
                  <td></td>
                  <td>Title</td>
                  <td>Opinion</td>
                  <td></td>
                  <td></td>
              </tr>
              <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= image_tag book.user.get_profile_image(80,80) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
                <% if book.favorited?(current_user) %>
                <td>
                    <!--# 一致するレコードが存在する＝すでにいいね済みの場合はdestroyアクションへ-->
                    <%= link_to book_favorites_path(book.id), method: :delete do %>
                        <i class="fas fa-heart" style="color:red;"></i>
                        <span style="color:red;"><%= book.favorites.count %></span>
                    <% end %>
                </td>
                <% else %>
                <td>
                    <!--# 一致するレコードが存在しない＝まだいいねしていない場合はcreateアクションへ-->
                    <%= link_to book_favorites_path(book.id), method: :post do %>
                        <i class="fas fa-heart" style="color:blue;"></i>
                        <span style="color:blue;"><%= book.favorites.count %></span>
                    <% end %>
                </td>
                <% end %>
                <td>コメント数：<%= book.book_comments.count %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>