config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  devise_for :users
  # devise_for :users, :controllers => {
  #   :registrations => 'devise/registrations'
  # }

  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  # resources :books do
  #   resource :favorites, only: [:create, :destroy]
  # end
  
  # resources :books, except: [:index] do
  #   resource :comments, only: [:create, :destroy]
  # end  
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
end

app/models/book.rb
class Book < ApplicationRecord
#   has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy  #Book.commentsで、投稿が所有するコメントを取得できる。
  
  def favorited?(user)
     favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
        @user = current_user
        @new_book = Book.new
    end
    
    
    def create
        @new_book = Book.new(book_params)
        @logging_in_user = current_user
        @new_book.user_id = @logging_in_user.id
        @user = @new_book.user
        
        if @new_book.save
          flash[:notice] = "You have created book successfully."
          redirect_to book_path(@new_book.id)
        else
          @books = Book.all
          render :index
        end
    end
    
    def show
        @new_book = Book.new
        @new_book_comment = BookComment.new
        @book = Book.find(params[:id])
        @user = @book.user
        @books = Book.all
    end
    
    def edit
        @book = Book.find(params[:id])     
        @user = @book.user
        unless current_user.id == @user.id
            redirect_to books_path
        end
    end
    
    def update
        @book = Book.find(params[:id])
        @user = @book.user
        
        if @book.update(book_params)
          flash[:notice] = "You have updated book successfully."
          redirect_to book_path(@book.id)
        else
          render :edit
        end
    end
    
    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
    end
        

    
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 pt-4 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <% if @book.errors.any? %>
        <div class="alert alert-warning">
          <p><%= @book.errors.count %> errors prohibited this book from being saved:</p>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="inputTitle">Title</label>
          <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"タイトル", class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="inputOpinion">Opinion</label>
          <%= f.text_area :body, autofocus: true, id:"inputOpinion", placeholder:"感想", class: "form-control" %>
        </div>
        
        <%= f.submit "Update Book", class: "btn btn-success" %>
        
        <p class="mt-4">
          <%= link_to "Show", book_path(@book.id)%> |
          <%= link_to "Back", books_path %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container pt-4 px-5 px-sm-0">
  <% if @new_book.errors.any? %>
    <div class="errors-box">
      <p><%= @new_book.errors.count %> errors prohibited this book from being saved:</p>
  
      <ul>
        <% @new_book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
        <%= render partial: 'layouts/side', locals: { user: @user, new_book: @new_book } %>
    </div>
    
    <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        
        <table class="table mb-5">
            <thead>
                <tr>
                    <td></td>
                    <td>Title</td>
                    <td>Opinion</td>
                    <td></td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                <% @books.each do |book| %>
                <tr>
                    <td>
                        <%= link_to user_path(book.user.id) do %>
                        <%= image_tag book.user.get_profile_image(80,80) %>
                        <% end %>
                    </td>
                    <td>
                        <%= link_to book_path(book.id) do %>
                        <%= book.title %>
                        <% end %>
                    </td>
                    <td><%= book.body %></td>
                    <% if book.favorited?(current_user) %>
                    <td>
                        <!--# 一致するレコードが存在する＝すでにいいね済みの場合はdestroyアクションへ-->
                        <%= link_to book_favorites_path(book.id), method: :delete do %>
                            <i class="fas fa-heart" style="color:red;"></i>
                            <span style="color:red;"><%= book.favorites.count %></span>
                        <% end %>
                    </td>
                    <% else %>
                    <td>
                        <!--# 一致するレコードが存在しない＝まだいいねしていない場合はcreateアクションへ-->
                        <%= link_to book_favorites_path(book.id), method: :post do %>
                            <i class="fas fa-heart" style="color:blue;"></i>
                            <span style="color:blue;"><%= book.favorites.count %></span>
                        <% end %>
                    </td>
                    <% end %>
                    <td>コメント数：<%= book.book_comments.count %></td>
                </tr>
                <% end %>
                
            </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p id = "notice"><%= flash[:notice] %></p>
<% end %>

<div class="container pt-4 px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
        <%= render partial: 'layouts/side', locals: { user: @user, new_book: @new_book } %>
    </div>
    
    <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table mb-5">
            <tbody>
                <tr>
                    <td>
                        <%= link_to user_path(@user.id) do %>
                          <%= image_tag @user.get_profile_image(100,100) %><br>
                          <%= @user.name %>
                        <% end %>
                    </td>
                    <td>
                        <%= link_to book_path(@book.id) do %>
                        <%= @book.title %>
                        <% end %>
                    </td>
                    <td><%= @book.body %></td>
                    <% if @book.favorited?(current_user) %>
                    <td>
                        <!--# 一致するレコードが存在する＝すでにいいね済みの場合はdestroyアクションへ-->
                        <%= link_to book_favorites_path(@book.id), method: :delete do %>
                            <i class="fas fa-heart" style="color:red;"></i>
                            <span style="color:red;"><%= @book.favorites.count %></span>
                        <% end %>
                    </td>
                    <% else %>
                    <td>
                        <!--# 一致するレコードが存在しない＝まだいいねしていない場合はcreateアクションへ-->
                        <%= link_to book_favorites_path(@book.id), method: :post do %>
                            <i class="fas fa-heart" style="color:blue;"></i>
                            <span style="color:blue;"><%= @book.favorites.count %></span>
                        <% end %>
                    </td>
                    <% end %>
                    <td>コメント数：<%= @book.book_comments.count %></td>
                    
                    <% if current_user == @user %>
                        <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
                        <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか?", class: "btn btn-sm btn-danger" %></td>
                    <% end %>
               </tr> 
            </tbody>
        </table>
        <table class="table table-borderless table-sm">
          <tbody>
            <% @book.book_comments.each do |book_comment| %>
              <tr>
                <td style="width: 15%">
                  <%= link_to user_path(book_comment.user.id) do %>
                    <%= image_tag book_comment.user.get_profile_image(60,60) %><br>
                    <%= book_comment.user.name %>
                  <% end %>
                </td>

                <% if book_comment.user == current_user %>
                  <td style="width: 65%">
                    <%= book_comment.comment %>
                  </td>
                  <td style="width: 20%">
                    <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger w-10 py-1" %>
                  </td>
                <% else %>
                  <td style="width: 85%">
                    <%= book_comment.comment %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>

        <div>
          <%= form_with model: [@book, @new_book_comment] do |f| %>
            <div class="form-group">
              <%= f.text_area :comment, rows: '5', class: "form-control" %>
            </div>

            <%= f.submit '送信', class: "btn btn-secondary" %>
          <% end %>
        </div>
    </div>
  </div>
</div>