config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  devise_for :users
  # devise_for :users, :controllers => {
  #   :registrations => 'devise/registrations'
  # }

  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  # resources :books do
  #   resource :favorites, only: [:create, :destroy]
  # end
  
  # resources :books, except: [:index] do
  #   resource :comments, only: [:create, :destroy]
  # end  
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
end

app/views/layouts/_side.html.erb
<main class="side_area">
    <h2>User info</h2>
    
    <table class="table mb-5">
        <tbody>
            <%= image_tag user.get_profile_image(100,100) %>
            <tr>
                <th>name</th>
                <th><%= user.name %></th>
            </tr>
            <tr>
                <th>introduction</th>
                <th><%= user.introduction %></th>
            </tr>
        </tbody>
    </table>
    
    <div>
        <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
    </div>


    <h2>New book</h2>
    
  
    <%= form_with model: @new_book, url: books_path do |f| %>
    <div class="form-group">
      <label for="inputTitle">Title</label>
      <%= f.text_field :title, id: "inputTitle", class: "form-control" %>
    </div>
    
    <div class="form-group">
      <label for="inputOpinion">Opinion</label>
      <%= f.text_area :body, id: "inputOpinion", class: "form-control" %>
    </div>
    
    <%= f.submit 'Create Book', class: "btn btn-success" %>
    <% end %>
    
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class="fas fa-home" style="color:white;"></i>
                Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users" style="color:white;"></i>
                Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open" style="color:white;"></i>
                Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt" style="color:white;"></i>
                logout
              <% end %>
            </li>
            <% else %>
            <li>
              <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home" style="color:white;"></i>
                Home
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link" style="color:white;"></i>
                About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus" style="color:white;"></i>
                sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt" style="color:white;"></i>
                login
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main>
      <%= yield %>
    </main>
    
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>